### ISSUE TITLE
404 on installation

### ISSUE THREAD

**Issue by callumacrae** [userapp-io/passport-userapp#2]
I'm getting an error on installation through npm:

```
npm http GET https://registry.npmjs.org/passport-userapp
npm http 304 https://registry.npmjs.org/passport-userapp
npm http GET https://registry.npmjs.org/passport-userapp/-/passport-userapp-1.1.0.tgz
npm http 404 https://registry.npmjs.org/passport-userapp/-/passport-userapp-1.1.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/passport-userapp/-/passport-userapp-1.1.0.tgz
npm ERR! Error: 404 Not Found
npm ERR!     at WriteStream.<anonymous> (/usr/local/Cellar/node/0.10.21/lib/node_modules/npm/lib/utils/fetch.js:57:12)
npm ERR!     at WriteStream.EventEmitter.emit (events.js:117:20)
npm ERR!     at fs.js:1596:14
npm ERR!     at /usr/local/Cellar/node/0.10.21/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:103:5
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 13.1.0
npm ERR! command "/usr/local/Cellar/node/0.10.21/bin/node" "/usr/local/bin/npm" "install" "--save" "passport-userapp"
npm ERR! cwd /Applications/XAMPP/xamppfiles/htdocs/dirname
npm ERR! node -v v0.10.21
npm ERR! npm -v 1.3.11
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Applications/XAMPP/xamppfiles/htdocs/dirname/npm-debug.log
npm ERR! not ok code 0
```

npm-debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/0.10.21/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'passport-userapp' ]
2 info using npm@1.3.11
3 info using node@v0.10.21
4 warn package.json DirName@0.0.0 No repository field.
5 warn package.json DirName@0.0.0 No README data
6 verbose readDependencies using package.json deps
7 verbose cache add [ 'passport-userapp', null ]
8 verbose cache add name=undefined spec="passport-userapp" args=["passport-userapp",null]
9 verbose parsed url { protocol: null,
9 verbose parsed url   slashes: null,
9 verbose parsed url   auth: null,
9 verbose parsed url   host: null,
9 verbose parsed url   port: null,
9 verbose parsed url   hostname: null,
9 verbose parsed url   hash: null,
9 verbose parsed url   search: null,
9 verbose parsed url   query: null,
9 verbose parsed url   pathname: 'passport-userapp',
9 verbose parsed url   path: 'passport-userapp',
9 verbose parsed url   href: 'passport-userapp' }
10 silly lockFile 6b5d2b09-passport-userapp passport-userapp
11 verbose lock passport-userapp /Users/callumacrae/.npm/6b5d2b09-passport-userapp.lock
12 silly lockFile 6b5d2b09-passport-userapp passport-userapp
13 silly lockFile 6b5d2b09-passport-userapp passport-userapp
14 verbose addNamed [ 'passport-userapp', '' ]
15 verbose addNamed [ null, '*' ]
16 silly lockFile 2f8414dd-passport-userapp passport-userapp@
17 verbose lock passport-userapp@ /Users/callumacrae/.npm/2f8414dd-passport-userapp.lock
18 silly addNameRange { name: 'passport-userapp', range: '*', hasData: false }
19 verbose url raw passport-userapp
20 verbose url resolving [ 'https://registry.npmjs.org/', './passport-userapp' ]
21 verbose url resolved https://registry.npmjs.org/passport-userapp
22 info trying registry request attempt 1 at 17:45:21
23 verbose etag "EL1H95J7EJ3VWFKLCS90BDJUH"
24 http GET https://registry.npmjs.org/passport-userapp
25 http 304 https://registry.npmjs.org/passport-userapp
26 silly registry.get cb [ 304,
26 silly registry.get   { date: 'Mon, 31 Mar 2014 16:45:21 GMT',
26 silly registry.get     server: 'CouchDB/1.5.0 (Erlang OTP/R14B04)',
26 silly registry.get     etag: '"EL1H95J7EJ3VWFKLCS90BDJUH"',
26 silly registry.get     'content-length': '0',
26 silly registry.get     'accept-ranges': 'bytes',
26 silly registry.get     via: '1.1 varnish',
26 silly registry.get     'cache-control': 'max-age=1',
26 silly registry.get     'x-served-by': 'cache-v37-ASH, cache-lo83-LHR',
26 silly registry.get     'x-cache': 'MISS, MISS',
26 silly registry.get     'x-cache-hits': '0, 0',
26 silly registry.get     'x-timer': 'S1396284321.643424988,VS0,VS39,VE120,VE157',
26 silly registry.get     'keep-alive': 'timeout=10, max=50',
26 silly registry.get     connection: 'Keep-Alive' } ]
27 verbose etag passport-userapp from cache
28 silly addNameRange number 2 { name: 'passport-userapp', range: '*', hasData: true }
29 silly addNameRange versions [ 'passport-userapp',
29 silly addNameRange   [ '0.1.0',
29 silly addNameRange     '1.0.1',
29 silly addNameRange     '1.0.3',
29 silly addNameRange     '1.0.4',
29 silly addNameRange     '1.0.5',
29 silly addNameRange     '1.0.6',
29 silly addNameRange     '1.0.9',
29 silly addNameRange     '1.1.0' ] ]
30 verbose addNamed [ 'passport-userapp', '1.1.0' ]
31 verbose addNamed [ '1.1.0', '1.1.0' ]
32 silly lockFile 17983982-passport-userapp-1-1-0 passport-userapp@1.1.0
33 verbose lock passport-userapp@1.1.0 /Users/callumacrae/.npm/17983982-passport-userapp-1-1-0.lock
34 silly lockFile e9d056f4-erapp-passport-userapp-1-1-0-tgz https://registry.npmjs.org/passport-userapp/-/passport-userapp-1.1.0.tgz
35 verbose lock https://registry.npmjs.org/passport-userapp/-/passport-userapp-1.1.0.tgz /Users/callumacrae/.npm/e9d056f4-erapp-passport-userapp-1-1-0-tgz.lock
36 verbose addRemoteTarball [ 'https://registry.npmjs.org/passport-userapp/-/passport-userapp-1.1.0.tgz',
36 verbose addRemoteTarball   '4d56878b7c31d4950a765d38616d059116c0c2ae' ]
37 info retry fetch attempt 1 at 17:45:22
38 verbose fetch to= /var/folders/xf/2p002c7d0x344lclv60xd2900000gn/T/npm-36309-YiehBdqp/1396284322156-0.4735150979831815/tmp.tgz
39 http GET https://registry.npmjs.org/passport-userapp/-/passport-userapp-1.1.0.tgz
40 http 404 https://registry.npmjs.org/passport-userapp/-/passport-userapp-1.1.0.tgz
41 error fetch failed https://registry.npmjs.org/passport-userapp/-/passport-userapp-1.1.0.tgz
42 silly lockFile e9d056f4-erapp-passport-userapp-1-1-0-tgz https://registry.npmjs.org/passport-userapp/-/passport-userapp-1.1.0.tgz
43 silly lockFile e9d056f4-erapp-passport-userapp-1-1-0-tgz https://registry.npmjs.org/passport-userapp/-/passport-userapp-1.1.0.tgz
44 silly lockFile 17983982-passport-userapp-1-1-0 passport-userapp@1.1.0
45 silly lockFile 17983982-passport-userapp-1-1-0 passport-userapp@1.1.0
46 silly lockFile 2f8414dd-passport-userapp passport-userapp@
47 silly lockFile 2f8414dd-passport-userapp passport-userapp@
48 error Error: 404 Not Found
48 error     at WriteStream.<anonymous> (/usr/local/Cellar/node/0.10.21/lib/node_modules/npm/lib/utils/fetch.js:57:12)
48 error     at WriteStream.EventEmitter.emit (events.js:117:20)
48 error     at fs.js:1596:14
48 error     at /usr/local/Cellar/node/0.10.21/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:103:5
48 error     at Object.oncomplete (fs.js:107:15)
49 error If you need help, you may report this log at:
49 error     <http://github.com/isaacs/npm/issues>
49 error or email it to:
49 error     <npm-@googlegroups.com>
50 error System Darwin 13.1.0
51 error command "/usr/local/Cellar/node/0.10.21/bin/node" "/usr/local/bin/npm" "install" "--save" "passport-userapp"
52 error cwd /Applications/XAMPP/xamppfiles/htdocs/dirname
53 error node -v v0.10.21
54 error npm -v 1.3.11
55 verbose exit [ 1, true ]
```

Possibly an issue with @npm, but I don't think that it is an issue with me—other things are installing fine.

**Comment by callumacrae** [comment]
It's installing fine through the european registry, so I think it's almost certainly an issue with @npm.

**Comment by timothyej** [comment]
Thanks for the notice! We've had problems with npm before, but I will take a quick look at it.
